import {VrouwenVerslag} from './VrouwenVerslag';
import type {VrouwenKalenderBron} from './VrouwenSchermen';
import {LockSimple} from '@phosphor-icons/react/dist/csr/LockSimple';
import {LockSimpleOpen} from '@phosphor-icons/react/dist/csr/LockSimpleOpen';
import {WasmandTekening} from '../components/Wasmand';
import {VrouwenMeldingen} from './VrouwenMeldingen';
import {useCallback,useEffect,useState} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import {useAuth} from '../lib/auth';
import {supabase} from '../lib/supabase';
import {clubRpc,clubPunten,CLUB_POSITIES,CLUB_LABELS,type ClubData,type ClubKeuze,type ClubMatch} from '../lib/club';
import {Tactiekbord} from '../components/Veld';
import {VrouwenKalender,VrouwenHome,VrouwenLeden,VrouwenSpelerProfiel,VrouwenSupporterProfiel,VrouwenStatistieken} from './VrouwenSchermen';
import './VrouwenClub.css';
const functies=['supporter','speler','spelercoach','coach','verantwoordelijke'];
export function VrouwenClub({tab,detail,stand,kalenderBron}:{tab:string;detail?:string;stand?:{positie:number;punten:number;gespeeld:number;voor:number};kalenderBron?:VrouwenKalenderBron|null}){
 const {session}=useAuth();const nav=useNavigate();
 const [data,setData]=useState<ClubData|null>(null),[fout,setFout]=useState(''),[bezig,setBezig]=useState(false),[bericht,setBericht]=useState('');
 const laden=useCallback(async()=>{if(!session){setData(null);return;}try{setData(await clubRpc<ClubData>('club_data'));setFout('');}catch(e){setFout(String((e as Error).message));}},[session]);
 useEffect(()=>{void laden();},[laden]);
 async function actie(naam:string,waarden:Record<string,unknown>){setBezig(true);setFout('');setBericht('');try{await clubRpc(naam,waarden);await laden();setBericht('Opgeslagen.');}catch(e){setFout((e as Error).message);}finally{setBezig(false);}}
 const [login,setLogin]=useState(false),[registreer,setRegistreer]=useState(false),[email,setEmail]=useState(''),[ww,setWw]=useState(''),[herhaal,setHerhaal]=useState(''),[naam,setNaam]=useState(''),[functie,setFunctie]=useState('speler');
 if(!session)return <section className="kaart v-club"><h2>Jouw clubaccount</h2><p>Gebruik hetzelfde account als bij Steca Juniors.</p><button className="knop" onClick={()=>setLogin(!login)}>Inloggen / account aanmaken</button>{login&&<form onSubmit={async e=>{e.preventDefault();setFout('');setBezig(true);try{if(registreer){if(ww!==herhaal)throw Error('De wachtwoorden verschillen.');const {error}=await supabase.auth.signUp({email,password:ww,options:{data:{account_type:'supporter',naam,club:'vrouwen',club_functie:functie}}});if(error)throw error;setBericht('Controleer je mailbox als bevestiging gevraagd wordt.');}else{const {error}=await supabase.auth.signInWithPassword({email,password:ww});if(error)throw error;}}catch(e){setFout((e as Error).message);}finally{setBezig(false);}}}><label><input type="checkbox" checked={registreer} onChange={e=>setRegistreer(e.target.checked)}/>Nieuw account</label>{registreer&&<><label>Naam<input required value={naam} onChange={e=>setNaam(e.target.value)}/></label><label>Bij de vrouwen ben ik<select value={functie} onChange={e=>setFunctie(e.target.value)}>{functies.map(f=><option key={f}>{f}</option>)}</select></label><p className="klein">Een beheerder bevestigt je spelers- of stafrol.</p></>}<label>E-mailadres<input type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Wachtwoord<input type="password" minLength={8} autoComplete={registreer?'new-password':'current-password'} required value={ww} onChange={e=>setWw(e.target.value)}/></label>{registreer&&<label>Herhaal wachtwoord<input type="password" required value={herhaal} onChange={e=>setHerhaal(e.target.value)}/></label>}<button className="knop" disabled={bezig}>{registreer?'Account aanmaken':'Inloggen'}</button><p><Link to="/wachtwoord-vergeten">Wachtwoord vergeten</Link></p></form>}{fout&&<p role="alert">{fout}</p>}{bericht&&<p role="status">{bericht}</p>}</section>;
 if(!data)return <section className="kaart">{fout?<><p role="alert">De ploeggegevens konden niet geladen worden: {fout}</p><button onClick={laden}>Opnieuw proberen</button></>:<p>Clubgegevens laden…</p>}</section>;
 const komend=data.matches.filter(m=>new Date(m.aftrap).getTime()>Date.now()&&m.thuis_score===null),ik=data.leden.find(l=>l.user_id===session.user.id);
 const m=detail?data.matches.find(m=>m.match_key===decodeURIComponent(detail)):komend[0];
 return <div className="v-club">{fout&&<p className="melding fout" role="alert">{fout}</p>}{bericht&&<p role="status" className="klein">{bericht}</p>}
 {tab===''&&<VrouwenHome data={data} stand={stand}>{komend[0]&&<Aanwezig toonSupporters data={data} match={komend[0]} bezig={bezig} actie={actie}/>}</VrouwenHome>}
 {tab==='kalender'&&<VrouwenKalender data={data} bron={kalenderBron} verslag={m=><VrouwenVerslag compact data={data} match={m} herlaad={laden}/>} inhoud={m=>Date.parse(m.aftrap)>Date.now()?<Aanwezig data={data} match={m} bezig={bezig} actie={actie}/>:<>{data.staf&&<Aanwezig data={data} match={m} bezig={bezig} actie={actie}/>}<Verslag data={data} match={m} actie={actie} bezig={bezig}/></>}/>}
 {tab==='profiel'&&<section className="kaart"><h1>Mijn profiel</h1><p>{ik?.naam??data.pronoleden.find(p=>p.user_id===session.user.id)?.naam}</p><p>Functie bij Steca Vrouwen: <b>{data.rol}</b></p><form onSubmit={e=>{e.preventDefault();void actie('club_vraag_rol',{p_functie:functie});}}><label>Andere functie aanvragen<select value={functie} onChange={e=>setFunctie(e.target.value)}>{functies.filter(f=>f!=='supporter').map(f=><option key={f}>{f}</option>)}</select></label><button disabled={bezig} className="knop">Aanvraag versturen</button></form><p className="klein">Je rol bij de mannen blijft hetzelfde.</p>{data.rol!=='supporter'&&<VrouwenMeldingen/>}<button className="knop licht" onClick={()=>supabase.auth.signOut()}>Uitloggen</button></section>}
 {tab==='leden'&&!detail&&<VrouwenLeden data={data} beheer={data.admin&&<section className="kaart"><h2>Ploegbeheer</h2>{import.meta.env.VITE_PLOEGEN_ENABLED==='true'&&<details><summary>Testcentrum vrouwen</summary><p>Fictieve wedstrijden om de schermen te controleren.</p><button disabled={bezig} onClick={()=>actie('club_testactie',{p_actie:'komend'})}>Komende testmatch</button> <button disabled={bezig} onClick={()=>actie('club_testactie',{p_actie:'gespeeld'})}>Gespeelde testmatch</button> <button disabled={bezig} onClick={()=>actie('club_testactie',{p_actie:'verwijderen'})}>Alle vrouwen-testmatches verwijderen</button></details>}{data.aanvragen.map(a=><p key={a.user_id}>{a.naam}: {a.functie} <button disabled={bezig} onClick={()=>actie('club_zet_lid',{p_user:a.user_id,p_functie:a.functie,p_speelt:['speler','spelercoach'].includes(a.functie)})}>Goedkeuren</button></p>)}<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void actie('club_zet_lid',{p_user:f.get('persoon'),p_functie:f.get('functie'),p_speelt:f.get('speelt')==='on'});}}><label>Account<select name="persoon" required>{data.pronoleden.map(p=><option key={p.user_id} value={p.user_id}>{p.naam}</option>)}</select></label><label>Functie<select name="functie">{functies.map(f=><option key={f}>{f}</option>)}</select></label><label><input name="speelt" type="checkbox"/>Speelt mee bij de vrouwen</label><button disabled={bezig} className="knop">Functie instellen</button></form></section>}/>}
 {tab==='leden'&&detail&&<VrouwenSpelerProfiel data={data} id={detail} herlaad={laden}/>}
 {tab==='supporters'&&detail&&<VrouwenSupporterProfiel data={data} user={detail} herlaad={laden}/>}
 {tab==='statistieken'&&<VrouwenStatistieken data={data}/>}
 {tab==='opstelling'&&<><h1>Opstelling</h1><label>Wedstrijd<select value={m?.match_key??''} onChange={e=>nav('/vrouwen/opstelling/'+encodeURIComponent(e.target.value))}>{data.matches.map(w=><option key={w.match_key} value={w.match_key}>{new Date(w.aftrap).toLocaleDateString('nl-BE')} · {w.thuis} - {w.uit}</option>)}</select></label>{m?<><p>{m.thuis} - {m.uit}</p><ClubVeld key={m.match_key} data={data} match={m} herlaad={laden}/>{data.staf&&Date.parse(m.aftrap)>Date.now()&&<><Aanwezig data={data} match={m} bezig={bezig} actie={actie}/><section className="kaart"><div className="v-wasmand-kop"><WasmandTekening vrouwen/><h2>Wasmand</h2></div><select aria-label="Wie neemt de wasmand mee" value={data.wasmand.find(w=>w.match_key===m.match_key)?.member_id??''} onChange={e=>actie('club_zet_wasmand',{p_match:m.match_key,p_lid:e.target.value})}><option value="" disabled>Kies een clublid</option>{data.leden.filter(l=>l.status==='actief'&&l.functie!=='supporter').map(l=><option key={l.id} value={l.id}>{l.naam}</option>)}</select></section></>}</>:<p>Er is nog geen volgende match.</p>}</>}
 {tab==='kantine'&&<><h1>De Kantine</h1>{!detail?<><p className="zacht">Een plek waar iedereen het beter weet dan de coach. Stel je Dream V samen, voorspel de uitslag en bewijs dat je er ook iets van kent.</p><div className="kantine-start"><button className="kaart kantine-spel" onClick={()=>nav('/vrouwen/kantine/dream')}><span className="kantine-spel-nr" aria-hidden="true">V</span><strong>Dream V</strong><span>Stel jouw ideale Steca-ploeg samen.</span><span className="knop">Maak jouw Dream V &#8594;</span></button><button className="kaart kantine-spel" onClick={()=>nav('/vrouwen/kantine/prono')}><span className="kantine-spel-nr" aria-hidden="true">1-0</span><strong>Steca Vrouwen Pronostieken</strong><span>Voorspel de Steca-matchen en klim in het klassement.</span><span className="knop">Naar Steca Vrouwen Pronostieken &#8594;</span></button></div></>:<><p><Link className="knop licht klein" to="/vrouwen/kantine">&#8592; Terug naar De Kantine</Link></p>{detail==='dream'?<><div className="melding kantine-prive"><strong>MIJN DREAM V</strong><br/>Wordt automatisch priv&#233; bewaard bij je account.</div><ClubVeld data={data} dream herlaad={laden}/></>:<><h2>Steca Vrouwen Pronostieken</h2><p>Voor de gokkers onder ons...</p><div className="tabs"><Link className={detail==='prono'?'actief':''} to="/vrouwen/kantine/prono">Voorspellen</Link><Link className={detail==='stand'?'actief':''} to="/vrouwen/kantine/stand">Klassement</Link></div><section className="kaart"><h2>{detail==='stand'?'Prono-klassement':'Zo scoor je punten'}</h2><p><strong>10</strong> exacte score · <strong>5</strong> juist doelpuntenverschil (ook gelijkspel) · <strong>3</strong> juiste winnaar · <strong>0</strong> verkeerd.</p><p className="zacht klein">Alleen de hoogste score telt. 2-0 voorspeld en 4-2 gespeeld = 5 punten. 1-1 voorspeld en 2-2 gespeeld = 5. Invoer sluit bij de aftrap. Punten vanaf 80 minuten na aftrap zodra er een uitslag is; correcties worden herberekend. Bij gelijke punten deel je dezelfde plaats.</p></section>{detail==='stand'?<VrouwenPronoStand data={data}/>:<>{data.matches.slice().sort((a,b)=>a.aftrap.localeCompare(b.aftrap)).map(m=><Prono key={m.match_key} data={data} match={m} actie={actie} bezig={bezig}/>)}{!data.matches.length&&<p>Er zijn nog geen Steca-matchen beschikbaar.</p>}</>}</>}</>}</>}
 {tab==='match'&&m&&<><VrouwenVerslag data={data} match={m} herlaad={laden}/>{data.staf&&<Aanwezig data={data} match={m} bezig={bezig} actie={actie}/>}<Verslag data={data} match={m} actie={actie} bezig={bezig}/></>}
 </div>;
}
type Actie=(naam:string,waarden:Record<string,unknown>)=>Promise<void>;
function Aanwezig({data,match,actie,bezig,toonSupporters=false}:{data:ClubData;match:ClubMatch;actie:Actie;bezig:boolean;toonSupporters?:boolean}){
 const [namen,setNamen]=useState(false),[anderen,setAnderen]=useState(false),[ultras,setUltras]=useState(false);
 const alle=data.aanwezigheden.filter(a=>a.match_key===match.match_key),eigen=alle.find(a=>a.user_id===data.user_id),spelers=data.leden.filter(l=>l.status==='actief'&&l.speelt),isSpeler=spelers.some(l=>l.user_id===data.user_id);
 const statussen=['aanwezig','afwezig','onzeker'];const fans=alle.filter(a=>!a.speler&&a.status==='aanwezig');
 const komend=Date.parse(match.aftrap)>Date.now();
 const knoppen=<div className="status-knoppen">{statussen.map(s=><button key={s} disabled={bezig} className={s+(eigen?.status===s?' actief':'')} aria-pressed={eigen?.status===s} onClick={()=>actie('club_aanwezig',{p_match:match.match_key,p_status:s})}>{s[0].toUpperCase()+s.slice(1)}</button>)}</div>;
 return <section><h3>{!komend?'Aanwezigheden':isSpeler?'Ben je erbij?':'Wie is erbij?'}</h3>{isSpeler&&komend&&<>{knoppen}<p className="aanwezig-bevestiging">{eigen?'Je staat als '+eigen.status+'.':'Je hebt nog niet geantwoord.'}</p></>}
 <p className="klein zacht">{statussen.map(s=>`${s[0].toUpperCase()+s.slice(1)}: ${alle.filter(a=>a.speler&&a.status===s).length}`).join(' · ')} · Nog niets: {spelers.filter(l=>!alle.some(a=>(a.member_id===l.id||(l.user_id!==null&&a.user_id===l.user_id)))).length}</p>
 <button className="knop licht klein" aria-expanded={namen} onClick={()=>setNamen(!namen)}>{namen?'Namen verbergen':'Namen tonen'}</button>
 {namen&&<div>{[...statussen,'nog niets'].map(status=><div key={status}><h4>{status}</h4><div className="namen">{spelers.filter(l=>(alle.find(a=>(a.member_id===l.id||(l.user_id!==null&&a.user_id===l.user_id)))?.status??'nog niets')===status).map(l=><span key={l.id} className={status}>{l.naam}</span>)}</div></div>)}</div>}
 {data.staf&&<div><button className="knop licht klein" aria-expanded={anderen} onClick={()=>setAnderen(!anderen)}>{anderen?'Sluiten':'Aanwezigheden aanpassen'}</button>{anderen&&<ul className="lijst omrand">{spelers.map(l=><li key={l.id} className="rij"><span>{l.naam}</span>{<select aria-label={'Aanwezigheid '+l.naam} disabled={bezig} value={alle.find(a=>(a.member_id===l.id||(l.user_id!==null&&a.user_id===l.user_id)))?.status??''} onChange={e=>actie('club_aanwezig_lid',{p_match:match.match_key,p_status:e.target.value,p_lid:l.id})}><option value="" disabled>Nog niets</option>{statussen.map(s=><option key={s}>{s}</option>)}</select>}</li>)}</ul>}</div>}
 {toonSupporters&&<section className="supporter-aanwezigheid"><div className="rij"><strong>Supporters</strong><button className="tekst-knop" aria-expanded={ultras} onClick={()=>setUltras(!ultras)}>{ultras?'Supporters verbergen':'Supporters tonen'}</button></div><p className="klein zacht">Deze supporters zijn erbij.</p>{!isSpeler&&<>{knoppen}<p className="aanwezig-bevestiging">{eigen?'Je staat als supporter op '+eigen.status+'.':'Je hebt als supporter nog niet geantwoord.'}</p></>}<p className="klein zacht">Aanwezig: {fans.length}</p>{ultras&&<div className="namen">{fans.map(a=><span key={a.user_id} className="aanwezig">{a.naam}</span>)}{!fans.length&&<p>Nog geen supporters op aanwezig.</p>}</div>}</section>}
 </section>;
}
function ClubVeld({data,match,dream=false,herlaad}:{data:ClubData;match?:ClubMatch;dream?:boolean;herlaad:()=>Promise<void>}){
 const opgeslagen=dream?data.dream:data.opstellingen.find(o=>o.match_key===match?.match_key);const [keuze,setKeuze]=useState<ClubKeuze>(opgeslagen?.keuze??{}),[slotjes,setSlotjes]=useState<string[]>(!dream&&opgeslagen&&'slotjes' in opgeslagen?(opgeslagen.slotjes as string[]):[]),[versie,setVersie]=useState(opgeslagen?.versie??0),[fout,setFout]=useState(''),[bezig,setBezig]=useState(false);
 useEffect(()=>{setKeuze(opgeslagen?.keuze??{});setVersie(opgeslagen?.versie??0);setSlotjes(!dream&&opgeslagen&&'slotjes' in opgeslagen?(opgeslagen.slotjes as string[]):[]);},[opgeslagen,dream]);
 const mag=dream||(data.staf&&!!match&&Date.parse(match.aftrap)>Date.now()),spelers=data.leden.filter(l=>l.status==='actief'&&l.speelt&&(dream||data.aanwezigheden.some(a=>a.match_key===match?.match_key&&(a.member_id===l.id||(l.user_id!==null&&a.user_id===l.user_id))&&a.status==='aanwezig')));
 async function bewaar(k:ClubKeuze,s=slotjes){if(bezig)return;setBezig(true);setFout('');try{const v=await clubRpc<number>(dream?'club_bewaar_dream':'club_bewaar_opstelling',{p_keuze:k,p_versie:versie,...(!dream?{p_match:match?.match_key,p_slotjes:s}:{})});setKeuze(k);setSlotjes(s);setVersie(v);await herlaad();}catch(e){setFout((e as Error).message);}finally{setBezig(false);}}
 return <section className="kaart"><p className="klein" role="status">{bezig?'Opslaan…':mag?'Wijzigingen worden automatisch opgeslagen.':''}</p>{fout&&<p role="alert">{fout} <button onClick={herlaad}>Herlaad</button></p>}<Tactiekbord formatie="4-3-3" zaal namen={Object.fromEntries(CLUB_POSITIES.map(p=>[p,data.leden.find(l=>l.id===keuze[p])?.naam]))} slotjes={slotjes}/>{mag&&<><div className="v-posities">{CLUB_POSITIES.map(p=><label key={p}>{CLUB_LABELS[p]??p.replace('BANK','Bank ')}<select disabled={bezig||slotjes.includes(p)} value={keuze[p]??''} onChange={e=>bewaar({...keuze,[p]:e.target.value||null})}><option value="">Niemand</option>{spelers.filter(l=>l.id===keuze[p]||!Object.values(keuze).includes(l.id)).map(l=><option key={l.id} value={l.id}>{l.naam}</option>)}</select>{!dream&&<button type="button" className="knop licht positie-slot" aria-label={(CLUB_LABELS[p]??p)+': '+(slotjes.includes(p)?'ontgrendelen':'vergrendelen')} aria-pressed={slotjes.includes(p)} disabled={bezig||!keuze[p]} onClick={()=>bewaar(keuze,slotjes.includes(p)?slotjes.filter(s=>s!==p):[...slotjes,p])}>{slotjes.includes(p)?<LockSimple size={22} weight="fill"/>:<LockSimpleOpen size={22}/>}</button>}</label>)}</div><button className="knop" disabled={bezig} onClick={()=>{const vast=Object.entries(keuze).filter(([p])=>slotjes.includes(p));const vrij=spelers.filter(l=>!vast.some(([,id])=>id===l.id)).map(l=>l.id);for(let i=vrij.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[vrij[i],vrij[j]]=[vrij[j],vrij[i]];}void bewaar(Object.fromEntries(CLUB_POSITIES.map(p=>[p,slotjes.includes(p)?keuze[p]:vrij.shift()??null])));}}>Loot de vrije plaatsen</button></>}</section>;
}
function VrouwenPronoStand({data}:{data:ClubData}){
 const rijen=data.pronoleden.map(p=>{let punten=0,exact=0,verschil=0,winnaar=0,gespeeld=0;for(const r of data.pronos.filter(r=>r.user_id===p.user_id)){const m=data.matches.find(m=>m.match_key===r.match_key);if(!m||m.thuis_score===null||m.uit_score===null||Date.parse(m.aftrap)+80*60000>Date.now())continue;const n=clubPunten(r.thuis,r.uit,m.thuis_score,m.uit_score);punten+=n;gespeeld++;if(n===10)exact++;if(n===5)verschil++;if(n===3)winnaar++;}return {...p,punten,exact,verschil,winnaar,gespeeld};}).sort((a,b)=>b.punten-a.punten||a.naam.localeCompare(b.naam));
 return <div className="tabel-wrap"><table className="tabel"><thead><tr><th>#</th><th>Naam</th>{['Punten','Exact','Verschil','Winnaar','Matchen'].map(k=><th className="num" key={k}>{k}</th>)}</tr></thead><tbody>{rijen.map(p=><tr key={p.user_id} className={p.user_id===data.user_id?'eigen':''}><td>{rijen.findIndex(r=>r.punten===p.punten)+1}</td><td>{p.naam}{p.user_id===data.user_id?' (jij)':''}</td>{[p.punten,p.exact,p.verschil,p.winnaar,p.gespeeld].map((n,i)=><td className="num" key={i}>{i===0?<strong>{n}</strong>:n}</td>)}</tr>)}</tbody></table>{!rijen.length&&<p>Er zijn nog geen actieve deelnemers.</p>}</div>;
}
function Prono({data,match,actie,bezig}:{data:ClubData;match:ClubMatch;actie:Actie;bezig:boolean}){
 const p=data.pronos.find(p=>p.match_key===match.match_key&&p.user_id===data.user_id),open=Date.parse(match.aftrap)>Date.now()&&match.thuis_score===null;
 return <section className="kaart"><p className="zacht klein">{new Date(match.aftrap).toLocaleString('nl-BE',{timeZone:'Europe/Brussels'})} · {open?'Open tot de aftrap':'Gesloten'}</p><h3>{match.thuis} - {match.uit}</h3><form key={JSON.stringify(p)} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void actie('club_bewaar_prono',{p_match:match.match_key,p_thuis:Number(f.get('thuis')),p_uit:Number(f.get('uit'))});}}><div className="prono-invoer"><label>{match.thuis}<input aria-label={'Voorspelde score '+match.thuis} name="thuis" inputMode="numeric" type="number" min="0" max="99" required disabled={!open||bezig} defaultValue={p?.thuis}/></label><strong>-</strong><label>{match.uit}<input aria-label={'Voorspelde score '+match.uit} name="uit" inputMode="numeric" type="number" min="0" max="99" required disabled={!open||bezig} defaultValue={p?.uit}/></label></div>{open&&<button className="knop" disabled={bezig}>{p?'Pronostiek aanpassen':'Pronostiek vastleggen'}</button>}{!open&&!p&&<p className="zacht">Geen voorspelling ingevuld.</p>}</form></section>;
}
function Verslag({data,match,actie,bezig}:{data:ClubData;match:ClubMatch;actie:Actie;bezig:boolean}){const op=data.opstellingen.find(o=>o.match_key===match.match_key),gekozen=data.leden.filter(l=>op&&Object.values(op.keuze).includes(l.id));return <>{gekozen.length>=4&&data.leden.some(l=>l.user_id===data.user_id&&l.speelt&&l.status==='actief')&&data.aanwezigheden.some(a=>a.match_key===match.match_key&&a.user_id===data.user_id&&a.status==='aanwezig')&&match.thuis_score!==null&&Date.now()>=Date.parse(match.aftrap)+80*60000&&Date.now()<Date.parse(match.aftrap)+24*3600000&&<form className="kaart" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void actie('club_stem',{p_match:match.match_key,p_eerste:f.get('eerste'),p_tweede:f.get('tweede'),p_derde:f.get('derde')});}}><h2>Speelster van de match</h2>{['eerste','tweede','derde'].map(k=><label key={k}>{k}<select name={k} required><option value="">Kies</option>{gekozen.filter(l=>l.user_id!==data.user_id).map(l=><option value={l.id} key={l.id}>{l.naam}</option>)}</select></label>)}<button disabled={bezig} className="knop">Stemmen</button></form>}</>;}
