import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {supabase} from '../lib/supabase';
import {useAuth} from '../lib/auth';
import {useAsync,foutTekst} from '../lib/useAsync';
import {seizoenNu} from '../lib/badgeCatalogus';
import {magBadgesTesten} from '../lib/badges';
import {FAN_BADGES,berekenFans,type FanBadge,type FanData} from '../lib/supporterBadges';
import {Fout,Laden} from './Layout';

function useFans(){const [v,setV]=useState(0);useEffect(()=>{const f=()=>setV(x=>x+1);window.addEventListener('supporter-badges',f);return()=>window.removeEventListener('supporter-badges',f);},[]);return useAsync(async()=>{const {data,error}=await supabase.rpc('supporter_klassement_data');if(error)throw error;return data as FanData;},[v]);}
export function SupporterBadgeIcoon({badge:b}:{badge:FanBadge}){
 const G='#e2b63c',R='#f5eedb',Z='#292929';
 return <svg className="badge-icoon" viewBox="0 0 100 100" role="img" aria-label={b.titel}><circle cx="50" cy="50" r="48" fill={Z} stroke={R} strokeWidth="2"/>
 {b.icoon==='bus'?<g stroke={Z} strokeWidth="2"><rect x="20" y="24" width="60" height="46" rx="8" fill={G}/><rect x="27" y="31" width="46" height="21" rx="2" fill={R}/><path d="M50 31v21"/><circle cx="30" cy="61" r="4" fill={R}/><circle cx="70" cy="61" r="4" fill={R}/><path d="M27 71v5m46-5v5" stroke={R} strokeWidth="6"/></g>:
 b.icoon==='sjaal'?<g><path d="M18 30h64v24H18z" fill={R}/><path d="M30 30h13v24H30zm26 0h13v24H56z" fill={G}/><path d="M18 54v9m7-9v9m50-9v9m7-9v9" stroke={R} strokeWidth="3"/></g>:
 b.icoon==='shirt'?<g><path d="m33 24-15 9 7 16 10-5v30h30V44l10 5 7-16-15-9q-17 15-34 0" fill={R}/><path d="M35 45h30v13H35z" fill={G}/></g>:
 b.icoon==='kroon'?<path d="m21 32 15 10 14-22 14 22 15-10-7 36H28Z" fill={G} stroke={R} strokeWidth="2"/>:
 b.icoon==='beker'?<g fill="none" stroke={G} strokeWidth="5"><path d="M32 24h36v22q-2 17-18 17T32 46Z" fill={G}/><path d="M31 31H20v11q0 13 16 13m33-24h11v11q0 13-16 13M50 63v15m-15 2h30"/></g>:
 <path d="m50 19 9 20 23 2-17 16 5 23-20-12-20 12 5-23-17-16 23-2Z" fill={G}/>}
 {b.aantal&&<text x="50" y="87" textAnchor="middle" fontSize="23" fontWeight="900" fontFamily="Arial" fill={G} stroke={Z} strokeWidth="3" paintOrder="stroke">{b.aantal}</text>}
 </svg>;
}
function FanProfiel({rij}:{rij:ReturnType<typeof berekenFans>[number]}){return <section className="kaart"><h2>{rij.naam}</h2><p>{rij.matchen} matchen bijgewoond · {rij.uit} uitmatchen</p><h3>Supportersbadges</h3>{!rij.badges.length&&<p>Nog geen badges verdiend.</p>}<div className="badge-test-grid">{rij.badges.map(b=>{const badge=FAN_BADGES.find(x=>x.id===b.badge);return badge?<article className="badge-test-kaart" key={b.badge+(b.seizoen??'')}><SupporterBadgeIcoon badge={badge}/><strong>{badge.titel}</strong>{b.seizoen&&<small>{b.seizoen.replace('-','/')}</small>}<span>{badge.uitleg}</span></article>:null;})}</div></section>;}
export function SupporterProfiel(){const {supporter}=useAuth();const info=useFans();const rij=info.data&&berekenFans(info.data,null).find(p=>p.user_id===supporter?.user_id);return <><h1>Mijn supportersprofiel</h1><Fout tekst={info.fout}/>{info.laden?<Laden/>:rij?<FanProfiel rij={rij}/>:<p>Nog geen supportersprofiel gevonden.</p>}<p><Link className="knop" to="/supporter-klassement">Supportersklassement</Link></p><button className="knop licht" onClick={()=>supabase.auth.signOut()}>Uitloggen</button></>;}
export function SupporterKlassement(){const info=useFans();const [seizoen,setSeizoen]=useState(seizoenNu());const [persoon,setPersoon]=useState('');if(info.laden)return <Laden/>;if(!info.data)return <><Fout tekst={info.fout}/><button onClick={info.herlaad}>Opnieuw laden</button></>;const data=info.data;const rijen=berekenFans(data,seizoen||null);const seizoenen=[...new Set([seizoenNu(),...data.matches.map(m=>m.seizoen)])].sort().reverse();let rang=0;return <><h2>Supportersklassement</h2><p>Op deze ultras kunnen we rekenen. Alleen bijgewoonde, gespeelde matchen tellen mee.</p><label>Periode<select value={seizoen} onChange={e=>setSeizoen(e.target.value)}><option value="">Aller tijden</option>{seizoenen.map(s=><option key={s} value={s}>{s.replace('-','/')}</option>)}</select></label><div className="tabel-wrap"><table className="tabel"><thead><tr><th>#</th><th>Supporter</th><th>Matchen</th></tr></thead><tbody>{rijen.map((r,i)=>{if(i===0||rijen[i-1].aantal!==r.aantal)rang=i+1;return <tr key={r.id}><td>{rang}</td><td><button className="tekst-knop" onClick={()=>setPersoon(persoon===r.id?'':r.id)}>{r.naam}</button></td><td><strong>{r.aantal}</strong></td></tr>;})}</tbody></table></div>{!rijen.length&&<p>Nog geen supporters.</p>}{persoon&&rijen.find(r=>r.id===persoon)&&<FanProfiel rij={rijen.find(r=>r.id===persoon)!}/>}</>;}
export function SupporterBadgesTest(){const info=useFans();const rechten=useAsync(magBadgesTesten);const [persoon,setPersoon]=useState('');const [naam,setNaam]=useState('');const [seizoen,setSeizoen]=useState(seizoenNu());const [aantal,setAantal]=useState(5);const [fout,setFout]=useState<string|null>(null);const [ok,setOk]=useState('');const [bezig,setBezig]=useState(false);
 async function doe(actie:string,data:Record<string,unknown>={}){setBezig(true);setFout(null);setOk('');try{const {error}=await supabase.rpc('supporter_testactie',{p_actie:actie,p_data:{persoon,seizoen,...data}});if(error)throw error;window.dispatchEvent(new Event('supporter-badges'));setOk('Opgeslagen. Klassement en badges zijn opnieuw berekend.');}catch(e){setFout(foutTekst(e));}finally{setBezig(false);}}
 if(info.laden||rechten.laden)return <Laden/>;if(!rechten.data)return <p>Alleen de aangewezen testbeheerder kan dit onderdeel gebruiken.</p>;if(!info.data)return <Fout tekst={info.fout}/>;
 const data=info.data;const gekozen=berekenFans(data,null).find(p=>p.id===persoon);
 return <><h2>Supporters testen</h2><p>Alleen testdata. Geen meldingen en geen wijzigingen in de echte app. Klik op een badge om die aan de gekozen supporter toe te wijzen.</p><Fout tekst={fout??info.fout}/>{ok&&<p role="status" className="melding ok">{ok}</p>}
 <fieldset disabled={bezig}><legend>Testpersoon</legend><label>Supporter<select value={persoon} onChange={e=>setPersoon(e.target.value)}><option value="">Kies een supporter</option>{data.personen.map(p=><option key={p.id} value={p.id}>{p.naam}</option>)}</select></label><form onSubmit={e=>{e.preventDefault();void doe('persoon',{naam});}}><label>Extra testpersoon<input value={naam} onChange={e=>setNaam(e.target.value)} required minLength={2}/></label><button className="knop licht">Testpersoon toevoegen</button></form><button className="knop licht" onClick={()=>doe('eerste_match')}>Vier supporters eerste match invullen</button></fieldset>
 <fieldset disabled={bezig}><legend>Automatische berekening testen</legend><label>Seizoen<input value={seizoen} onChange={e=>setSeizoen(e.target.value)} pattern="[0-9]{4}-[0-9]{4}"/></label><label>Aantal uitmatchen<select value={aantal} onChange={e=>setAantal(Number(e.target.value))}>{[1,5,10,25,50,100].map(n=><option key={n}>{n}</option>)}</select></label><button className="knop" disabled={!persoon} onClick={()=>doe('reeks',{aantal})}>Testreeks toevoegen</button><button className="knop licht" disabled={!persoon} onClick={()=>{if(confirm('Alle gegenereerde supporter-testreeksen verwijderen?'))void doe('wis_reeks');}}>Testreeksen opruimen</button><p className="klein zacht">Deze testmatches staan alleen in het supportersklassement. Bestaande wedstrijden blijven behouden.</p><button className="knop licht" onClick={()=>doe('afsluiten',{afgerond:!data.afgerond.includes(seizoen)})}>{data.afgerond.includes(seizoen)?'Seizoen heropenen':'Seizoen afronden voor Perfect seizoen'}</button>
 {persoon&&<details><summary>Aanwezigheid per match aanpassen</summary><ul className="lijst">{data.matches.map(m=><li key={m.id}><label><input type="checkbox" checked={data.bezoeken.some(b=>b.persoon===persoon&&b.match===m.id)} onChange={e=>doe('bezoek',{match:m.id,aanwezig:e.target.checked})}/> {m.datum} · {m.label}{!m.gespeeld?' (nog te spelen)':''}</label></li>)}</ul></details>}</fieldset>
 <h3>Alle supportersbadges</h3><div className="badge-test-grid">{FAN_BADGES.map(b=>{const handmatig=data.testbadges.some(t=>t.persoon===persoon&&t.badge===b.id&&(t.seizoen??'')===(b.soort==='seizoen'?seizoen:''));return <button className="badge-test-kaart" key={b.id} disabled={!persoon||bezig} onClick={()=>doe('badge',{badge:b.id,badgeSeizoen:b.soort==='seizoen'?seizoen:'',toewijzen:!handmatig})}><SupporterBadgeIcoon badge={b}/><strong>{b.titel}</strong><span>{b.uitleg}</span><small>{handmatig?'Testbadge verwijderen':'Toewijzen als testbadge'}</small></button>;})}</div>{gekozen&&<FanProfiel rij={gekozen}/>}<SupporterKlassement/></>;
}
