import {useEffect,useState} from 'react';
import {clubRpc} from '../lib/club';
export type ClubBericht={id:string;tekst:string;actief:boolean;auteur:string;updated_at:string};
export const VROUWEN_BAND='vrouwen-lichtkrant-herladen';
export function VrouwenLichtkrantBeheer(){
 const [lijst,setLijst]=useState<ClubBericht[]>([]),[tekst,setTekst]=useState(''),[bewerkt,setBewerkt]=useState<ClubBericht|null>(null),[bezig,setBezig]=useState(false),[fout,setFout]=useState('');
 async function laad(){try{setLijst(await clubRpc<ClubBericht[]>('club_lichtkrant'));}catch(e){setFout((e as Error).message);}}
 useEffect(()=>{void laad();},[]);
 async function doe(velden:Record<string,unknown>){setBezig(true);setFout('');try{await clubRpc('club_bewaar_bericht',velden);setTekst('');setBewerkt(null);await laad();window.dispatchEvent(new Event(VROUWEN_BAND));}catch(e){setFout((e as Error).message);}finally{setBezig(false);}}
 return <section className="kaart"><h2>Lichtkrant</h2><p className="klein zacht">Beheer hier alle boodschappen van de vrouwenploeg.</p>{fout&&<p role="alert">{fout}</p>}<form onSubmit={e=>{e.preventDefault();void doe({p_id:bewerkt?.id??null,p_tekst:tekst,p_actief:bewerkt?.actief??true});}}><label>{bewerkt?'Boodschap aanpassen':'Nieuwe boodschap'}<input value={tekst} maxLength={140} required disabled={bezig} onChange={e=>setTekst(e.target.value)}/></label><button className="knop" disabled={bezig||!tekst.trim()}>{bewerkt?'Opslaan':'Toevoegen'}</button>{bewerkt&&<button type="button" className="knop licht" onClick={()=>{setBewerkt(null);setTekst('');}}>Annuleren</button>}</form><ul className="lijst omrand" style={{marginTop:12}}>{lijst.map(b=><li key={b.id}><p style={{opacity:b.actief?1:.6}}>{b.tekst}</p><p className="klein zacht">{b.auteur} · {b.actief?'Loopt mee':'Uit'}</p><div className="knoppen"><button className="knop licht klein" disabled={bezig} onClick={()=>{setBewerkt(b);setTekst(b.tekst);}}>Aanpassen</button><button className="knop licht klein" disabled={bezig} onClick={()=>doe({p_id:b.id,p_tekst:b.tekst,p_actief:!b.actief})}>{b.actief?'Uit':'Aan'}</button><button className="knop licht klein" disabled={bezig} onClick={()=>{if(confirm('Deze boodschap verwijderen?'))void doe({p_id:b.id,p_verwijder:true});}}>Verwijderen</button></div></li>)}</ul>{!lijst.length&&<p className="klein zacht">Nog geen boodschappen.</p>}</section>;
}
