import {supabase} from './supabase';
export type ClubLid={id:string;user_id:string|null;naam:string;functie:string;speelt:boolean;status:string;is_admin:boolean};
export type ClubMatch={match_key:string;seizoen:string;aftrap:string;thuis:string;uit:string;thuis_score:number|null;uit_score:number|null;is_test:boolean;reeks?:string;locaties?:{zaal:string;adres:string}[]};
export type ClubKeuze=Record<string,string|null>;
export type ClubStat={id:string;goals:number;assists:number;geel:number;rood:number};
export type ClubData={rol:string;admin:boolean;staf:boolean;user_id:string;leden:ClubLid[];aanvragen:{user_id:string;naam:string;functie:string}[];matches:ClubMatch[];aanwezigheden:{match_key:string;user_id:string;member_id?:string|null;naam:string;status:string;speler:boolean}[];opstellingen:{match_key:string;keuze:ClubKeuze;slotjes:string[];versie:number}[];verslagen:{match_key:string;statistieken:ClubStat[];verslag:string}[];pronos:{match_key:string;user_id:string;thuis:number;uit:number}[];dream:{keuze:ClubKeuze;versie:number}|null;stemmen:{match_key:string;eerste:string;tweede:string;derde:string}[];wasmand:{match_key:string;member_id:string}[];pronoleden:{user_id:string;naam:string}[]};
export async function clubRpc<T=void>(naam:string,velden:Record<string,unknown>={}):Promise<T>{const {data,error}=await supabase.rpc(naam,{p_club:'vrouwen',...velden});if(error)throw new Error(error.message);return data as T;}
export const CLUB_POSITIES=['GK','LB','RB','LW','RW','BANK1','BANK2','BANK3','BANK4','BANK5'];
export const CLUB_LABELS:Record<string,string>={GK:'Doelvrouw',LB:'Linksachter',RB:'Rechtsachter',LW:'Linksvoor',RW:'Rechtsvoor'};
export function clubPunten(thuis:number,uit:number,echtThuis:number,echtUit:number){if(thuis===echtThuis&&uit===echtUit)return 10;if(thuis-uit===echtThuis-echtUit)return 5;if(Math.sign(thuis-uit)===Math.sign(echtThuis-echtUit))return 3;return 0;}
export function clubStatistieken(data:ClubData,id:string,seizoen?:string){const totaal={goals:0,assists:0,geel:0,rood:0,gespeeld:0,cleansheets:0};for(const m of data.matches){if((seizoen&&m.seizoen!==seizoen)||m.thuis_score===null||m.uit_score===null||new Date(m.aftrap).getTime()+80*60000>Date.now())continue;const op=data.opstellingen.find(o=>o.match_key===m.match_key);if(op&&Object.values(op.keuze).includes(id)){totaal.gespeeld++;if(op.keuze.GK===id&&(m.thuis==='STECA VROUWEN'?m.uit_score:m.thuis_score)===0)totaal.cleansheets++;}const s=data.verslagen.find(v=>v.match_key===m.match_key)?.statistieken.find(s=>s.id===id);if(s){totaal.goals+=s.goals;totaal.assists+=s.assists;totaal.geel+=s.geel;totaal.rood+=s.geel===2?Math.max(1,s.rood):s.rood;}}return totaal;}
