/// <reference types="node" />
import {beforeAll,afterAll,it,expect} from 'vitest';
import {PGlite} from '@electric-sql/pglite';
import {readFileSync} from 'node:fs';
let db:PGlite;
beforeAll(async()=>{db=new PGlite();await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;
create table auth.users(id uuid primary key);
create function auth.uid() returns uuid language sql as $$select nullif(current_setting('test.uid',true),'')::uuid$$;
create function is_actief() returns boolean language sql as $$select auth.uid() is not null$$;
create function mag_testbadges_beheren() returns boolean language sql as $$select current_setting('test.admin',true)='yes'$$;
create table supporter_profiles(user_id uuid primary key,naam text,actief boolean default true);
create table matches(match_key text primary key,seizoen text,datum date,uur text,thuis_id int,uit_id int,status text,thuis text,uit text,bron text);
create function match_aftrap(date,text) returns timestamptz language sql as $$select $1::timestamptz$$;
create table supporter_attendance(match_key text,user_id uuid,status text,updated_at timestamptz default now(),primary key(match_key,user_id));`);
const sql=readFileSync(new URL('../../../supabase/app_schema.sql',import.meta.url),'utf8');await db.exec(sql.slice(sql.indexOf('-- Supportersklassement en badgeproef:')));
},30000);
afterAll(async()=>{await db?.close();});
it('blokkeert testmutaties zonder testbeheerder',async()=>{await db.exec("select set_config('test.admin','no',false)");await expect(db.query("select supporter_testactie('persoon','{\"naam\":\"Test Fan\"}')")).rejects.toThrow('testbeheerder');});
it('maakt eerste vier aanwezigen idempotent zonder echte matches te wijzigen',async()=>{await db.exec("select set_config('test.admin','yes',false);select supporter_testactie('eerste_match');select supporter_testactie('eerste_match');");expect((await db.query('select * from supporter_fans')).rows).toHaveLength(4);expect((await db.query('select * from supporter_bezoeken')).rows).toHaveLength(4);expect((await db.query('select * from matches')).rows).toHaveLength(0);});
it('voegt nieuwe supporter toe en telt eigen aanwezigheid in de data',async()=>{await db.exec(`insert into auth.users values('00000000-0000-0000-0000-000000000001');insert into supporter_profiles(user_id,naam) values('00000000-0000-0000-0000-000000000001','Nieuwe Fan');select set_config('test.uid','00000000-0000-0000-0000-000000000001',false);insert into matches values('echt','2026-2027','2020-01-01','15:00',152,1,'gespeeld','Steca','Tegenstander','scrape');insert into supporter_attendance(match_key,user_id,status) values('echt','00000000-0000-0000-0000-000000000001','aanwezig');`);const r=await db.query<{d:{personen:unknown[],bezoeken:unknown[]}}>('select supporter_klassement_data() as d');expect(r.rows[0].d.personen).toHaveLength(5);expect(r.rows[0].d.bezoeken).toHaveLength(5);});
it('kan bestaande aanwezigheid uitvinken en weigert onbekende badges',async()=>{const {rows}=await db.query<{id:string}>("select id from supporter_fans where naam='Nieuwe Fan'");const persoon=rows[0].id;await db.query("select supporter_testactie('bezoek',$1::jsonb)",[JSON.stringify({persoon,match:'echt',aanwezig:false})]);expect((await db.query<{status:string}>("select status from supporter_attendance where match_key='echt'")).rows[0].status).toBe('afwezig');await expect(db.query("select supporter_testactie('badge',$1::jsonb)",[JSON.stringify({persoon,badge:'onbekend',toewijzen:true})])).rejects.toThrow('Onbekende badge');});
it('schermt ruwe tabellen af en laat alleen authenticated de leesfunctie uitvoeren',async()=>{expect((await db.query<{ok:boolean}>("select has_table_privilege('authenticated','supporter_fans','INSERT') as ok")).rows[0].ok).toBe(false);expect((await db.query<{ok:boolean}>("select has_function_privilege('anon','supporter_klassement_data()','EXECUTE') as ok")).rows[0].ok).toBe(false);});
